"""empty message

Revision ID: 5862428d4fb9
Revises: b207e861c4c9
Create Date: 2021-06-25 18:40:56.862947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5862428d4fb9'
down_revision = 'b207e861c4c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
