"""empty message

Revision ID: d37e9f047645
Revises: ee0bccf6b5fd
Create Date: 2021-06-25 18:39:02.841518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd37e9f047645'
down_revision = 'ee0bccf6b5fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
