# Read more about setting it up
# https://medium.com/@ljmocic/deploying-react-application-to-aws-s3-using-github-actions-85addacaeace

name: Deploy Django app
on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch

  push:
    branches: [ main ]
  #pull_request:
  #  branches: [ main 
jobs:
  build:
    name: Build, test and publish app Docker images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Build the docker-compose stack
        run: docker network create my_services && docker-compose up --build -d

      - name: Get init logs
        run: docker-compose logs

      - name: Run test suite
        run: docker-compose exec -T web pytest

      - name: Publish image(s)
        run: |
          docker tag test_backend ${{ secrets.DOCKER_USERNAME}}/test_backend:${{ github.sha }} && \
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p "${{ secrets.DOCKER_PASSWORD }}"
          docker push ${{ secrets.DOCKER_USERNAME}}/test_backend:${{ github.sha }}
  deploy:
    if: github.ref == 'refs/heads/master'
    name: Run remote deploy script
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: appleboy/ssh-action@v0.0.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{secrets.SERVER_USERNAME}}
          key: ${{ secrets.SSH_KEY }}
          script: ./deploy-test_backend.sh